Entity40\FacilityUse:
  type: entity
  table: usos
  indexes:
    usos_pkey:
      columns: [id]
  fields:
    id:
      type: integer
      id: true
      strategy:
        generator: SEQUENCE
      sequenceGenerator:
        sequenceName: uso_ai
        allocationSize: 100
        initialValue: 1
  manyToOne:
    facility:
      targetEntity: Entity40\Facility
      inversedBy: facilityUses
    reservation:
      targetEntity: Entity40\Reservation
      inversedBy: facilityUses
