Entity40\Hotel:
  type: entity
  table: hoteles
  indexes:
    hoteles_pkey:
      columns: [id]
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    name:
      type: string
      column: nombre
    number_rooms:
      type: integer
      column: nro_piezas
    price_room:
      type: integer
      column: precio_pieza
    star_rating:
      type: integer
      column: estrellas


