Entity40\Reservation:
  type: entity
  table: reservas
  indexes:
    reservas_pkey:
      columns: [id]
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    arrival:
      type: date
      column: llegada
    duration:
      type: integer
      column: duracion
    payment_method:
      type: string
      column: medio_pago
  manyToOne:
    hotel:
      targetEntity: Entity40\hotel
      inversedBy: reservations
      joinColumn:
        name: hotel_id
        referencedColumnName: id
  oneToMany:
    facilityUses:
      targetEntity: Entity40\FacilityUse
      mappedBy: reservation
  oneToOne:
    review:
      targetEntity: Entity40\Review
      joinColumn:
        name: critica_id
        referencedColumnName: id
        onDelete: SET NULL
