Entity40\Review:
  type: entity
  table: criticas
  indexes:
    criticas_pkey:
      columns: [id]
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    description:
      type: string
      column: descripcion
    rating:
      type: integer
      column: nota
