Entity40\Hotel:
  type: entity
  table: hoteles
  indexes:
    hoteles_pkey:
      columns: [id]
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    name:
      type: string
      column: nombre
    number_rooms:
      type: integer
      column: nro_piezas
    price_room:
      type: integer
      column: precio_pieza
    star_rating:
      type: integer
      column: estrellas
  oneToOne:
    address:
      targetEntity: Entity40\Address
      joinColumn:
        name: direccion_id
        referencedColumnName: id
        onDelete: CASCADE
  oneToMany:
    facilities:
      targetEntity: Entity40\Facility
      mappedBy: hotel_id
      cascade: ["persist", "merge"]
    reservations:
      targetEntity: Entity40\Reservation
      mappedBy: hotel_id
      cascade: ['persist', 'merge']

