Entity37\Reservation:
  type: entity
  table: reserva
  indexes:
    reserva_pkey:
      columns: [idreserva]
  fields:
    id:
      type: integer
      id: true
      column: idreserva
      generator:
        strategy: AUTO
    date:
      type: date
      column: fecha
    time:
      type: time without time zone
      column: hora
    quantity:
      type: integer
      column: cantidad
  oneToOne:
    restaurantReservation:
      targetEntity: Entity37\ReservationRestaurant
      mappedBy: reservation
