Entity37\ReviewRestaurant:
  type: entity
  table: criticarestaurante
  indexes:
    criticarestaurante_pkey:
      columns: [idcritica]
  oneToOne:
    review:
      targetEntity: Entity37\Review
      joinColumn:
        name: idcritica
        referencedColumnName: idcritica
  manyToOne:
    author:
      targetEntity: Entity37\Client
      inversedBy: reviews
      joinColumn:
        name: telefono
        referencedColumnName: telefono
    restaurant:
      targetEntity: Entity37\Restaurant
      inversedBy: reviews
      joinColumn:
        name: rnombre
        referencedColumnName: rnombre
