Entity37\Schedule:
  type: entity
  table: horario
  indexes:
    horario_pkey:
      columns: [rnombre, dia]
  fields:
    day:
      type: integer
      column: dia
      id: true
    opening:
      type: time without time zone
      column: apertura
    closing:
      type: time without time zone
      column: cierre
  manyToOne:
    restaurant:
      targetEntity: Entity37\Restaurant
      inversedBy: schedule
      joinColumn:
        name: rnombre
        referencedColumnName: rnombre
